### ISSUE TITLE
Great Work! Quick Question

### ISSUE THREAD

**Issue by akinorhanemre** [0x7o/IF-replicate#2]
Hey Mate,

I have to say I am quite impressed by the agility you have to put a model that is this large to Replicate, I am working on img2img version of IF too. For my specific use case, I am aiming for super high support_noise_less_qsample_steps. Can we meet up for a quick question I have for you, I would very much appreciate it.

**Comment by 0x7o** [comment]
E-mail me, please. danil.kononyuk [at] ya.ru
